from datetime import datetime
from .event import Event, EventCreate, EventBase

# below is used when both retrieving and creating user data
class AppointmentBase(EventBase):
    ...


# below includes the data needed when creating a user
# other fields are expected to be autogenerated
class AppointmentCreate(EventCreate, AppointmentBase):
    ...


# below is used when retrieving User
class Appointment(Event, AppointmentBase):
    id: int
    # patient_id: int
    # doctor_id: int

    class Config:
        orm_mode = True