from typing import List

from pydantic import BaseModel

from .user import UserBase, User, UserCreate
from .enums import Role

# required class fields without the inherited fields
class PatientFields(BaseModel):
    medical_history: str

# below is used when both retrieving and creating user data
class PatientBase(UserBase, PatientFields):
    ...


# below includes the data needed when creating a doctor
# other fields are expected to be autogenerated
class PatientCreate(UserCreate, PatientBase):
    role: str = Role.patient.value
    ...


# below is used when retrieving User
class Patient(User, PatientBase):
    id: int

    # appointments: List[Appointment] = []

    class Config:
        orm_mode = True