"""removed patient id from appointment temo

Revision ID: b5bb11d93e33
Revises: 8a4ace41a886
Create Date: 2022-08-03 22:20:45.689674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bb11d93e33'
down_revision = '8a4ace41a886'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_patient_id_fkey', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'patient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('appointments_patient_id_fkey', 'appointments', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###
